http_proxy: ''
proxy_env:
  http_proxy: "{{ http_proxy }}"
  https_proxy: "{{ http_proxy }}"
  HTTP_PROXY: "{{ http_proxy }}"
  HTTPS_PROXY: "{{ http_proxy }}"

coreos_timezone: 'Europe/London'
etcd_servers_group: etcd_servers
api_servers_group: masters

# The docker container version to use for Kubernetes
kubernetes_version: v1.1.8_coreos.0

# The CIDR network to use for pod IPs. Each pod launched in the cluster will be
# assigned an IP out of this range. This network must be routable between all
# hosts in the cluster. In a default installation, the flannel overlay network
# will provide routing to this network.
kubernetes_pod_network: 10.2.0.0/16

# The CIDR network to use for service cluster VIPs (Virtual IPs).
# Each service will be assigned a cluster IP out of this range.
# This must not overlap with any IP ranges assigned to the POD_NETWORK,
# or other existing network infrastructure.
# Routing to these VIPs is handled by a local kube-proxy service to each host,
# and are not required to be routable between hosts.
kubernetes_service_ip_range: 10.3.0.0/24

# The VIP (Virtual IP) address of the Kubernetes API Service.
# If the SERVICE_IP_RANGE is changed above,
# this must be set to the first IP in that range.
kubernetes_service_ip: 10.3.0.1

# The VIP (Virtual IP) address of the cluster DNS service.
# This IP must be in the range of the SERVICE_IP_RANGE and cannot be the first
# IP in the range. This same IP must be configured on all worker nodes to
# enable DNS service discovery.
kubernetes_dns_service_ip: 10.3.0.10

# The kubelet wrapper script for use on CoreOS. This makes it easy to run the
# kubelet under rkt (recommended by CoreOS). Ships by default in CoreOS 962.0.0+
# but we include it here for backwards compatibility in the stable/beta channels.
# See https://coreos.com/kubernetes/docs/latest/kubelet-wrapper.html
kubernetes_kubelet_wrapper: https://raw.githubusercontent.com/coreos/coreos-overlay/master/app-admin/kubelet-wrapper/files/kubelet-wrapper

# kubernetes config dirs (used by master and worker)
kubernetes_config_dir: /etc/kubernetes
kubernetes_script_dir: /srv/kubernetes
kubernetes_cert_dir: "{{ kubernetes_config_dir }}/ssl"
kubernetes_manifest_dir: "{{ kubernetes_config_dir }}/manifests"
kubernetes_users_dir: "{{ kubernetes_config_dir }}/users"
kubernetes_podmaster_dir: "{{ kubernetes_script_dir }}/manifests"
