# config
- name: create kubernetes dirs
  file:
    path: "{{ item }}"
    state: directory
    mode: 0755
  with_items:
    - "{{ kubernetes_config_dir }}"
    - "{{ kubernetes_script_dir }}"
  become: yes
  tags:
    - k8s-worker

# kubelet-wrapper is only available on CoreOS 962.0.0+ so we make sure its here
# to ensure backwards compatability.
# See https://coreos.com/kubernetes/docs/latest/kubelet-wrapper.html
- name: download kubelet-wrapper
  become: yes
  get_url:
    url: "{{ kubernetes_kubelet_wrapper }}"
    dest: /opt/bin/kubelet-wrapper
    mode: 0775
  tags:
    - k8s-worker

# worker
- name: deploy kubelet service
  become: yes
  template:
    src: kubelet.service.j2
    dest: /etc/systemd/system/kubelet.service
  notify:
    - reload systemd
    - restart kubelet
  tags:
    - k8s-worker

- name: ensure kubelet is running
  become: yes
  service:
    name: kubelet
    state: started
    enabled: yes
  tags:
    - k8s-worker

- name: deploy k8s-worker manifests
  become: yes
  template:
    src: "{{ item.src }}"
    dest: "{{ item.dest }}"
  with_items:
    - src: worker-kubeconfig.yaml.j2
      dest: "{{ kubernetes_config_dir }}/worker-kubeconfig.yaml"
    - src: kube-proxy.yaml.j2
      dest: "{{ kubernetes_manifest_dir }}/kube-proxy.yaml"
  tags:
    - k8s-worker
