---
# create SkyDNS dns service
- name: create SkyDNS pod file
  become: yes
  template:
    src: skydns-rc.yaml.j2
    dest: "{{ kubernetes_manifest_dir }}/skydns-rc.yaml"
  tags:
    - addons
    - skydns

- name: create SkyDNS service file
  become: yes
  template:
    src: skydns-svc.yaml.j2
    dest: "{{ kubernetes_manifest_dir }}/skydns-svc.yaml"
  tags:
    - addons
    - skydns

# @todo - we need to call kubelet here to provision the skydns replication
# controller and sydns service properly
