- name: deploy calico-node service
  become: yes
  template:
    src: calico-node.service.j2
    dest: /etc/systemd/system/calico-node.service
    owner: root
    group: root
    mode: 0644
  notify:
    - reload systemd
    - restart calico-node
  tags:
    - kube-master

- name: ensure calico-node is running
  become: yes
  service:
    name: calico-node
    state: started
    enabled: yes
  tags:
    - kube-master

- name: create calico-system namespace file
  become: yes
  copy:
    src: calico-system.yaml
    dest: "{{ kubernetes_addons_dir }}/calico-system.yaml"
  tags:
    - kube-master
    - kubernetes

- name: Create calico-system namespace
  become: yes
  kube:
    resource: namespace
    name: calico-system
    filename: "{{ kubernetes_addons_dir }}/calico-system.yaml"
    state: present
  run_once: true
  tags:
    - kube-master
    - kubernetes
